// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EHM_Survey_App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241214074743_AddSurveyFields")]
    partial class AddSurveyFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EHM_Survey_App.Models.Store", b =>
            {
                b.Property<int>("StoreId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                b.Property<string>("StoreCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("StoreName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("StoreId");

                b.ToTable("Stores");
            });

            modelBuilder.Entity("EHM_Survey_App.Models.Survey", b =>
            {
                b.Property<int>("SurveyId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyId"));

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<bool>("IsRequired")
                    .HasColumnType("bit");

                b.Property<int>("Order")
                    .HasColumnType("int");

                b.Property<string>("Question")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("QuestionOptions")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("QuestionType")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("StoreId")
                    .HasColumnType("int");

                b.HasKey("SurveyId");

                b.HasIndex("StoreId");

                b.ToTable("Surveys");
            });

            modelBuilder.Entity("EHM_Survey_App.Models.SurveyResponse", b =>
            {
                b.Property<int>("ResponseId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseId"));

                b.Property<bool>("Abandoned")
                    .HasColumnType("bit");

                b.Property<float>("CompletionTime")
                    .HasColumnType("real");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsVerified")
                    .HasColumnType("bit");

                b.Property<int>("NpsScore")
                    .HasColumnType("int");

                b.Property<string>("Response")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("StoreId")
                    .HasColumnType("int");

                b.Property<DateTime>("SubmissonDate")
                    .HasColumnType("datetime2");

                b.Property<int>("SurveyId")
                    .HasColumnType("int");

                b.Property<string>("UserAgent")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("VerificationCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("ResponseId");

                b.HasIndex("StoreId");

                b.ToTable("SurveyResponses");
            });

            modelBuilder.Entity("EHM_Survey_App.Models.Survey", b =>
            {
                b.HasOne("EHM_Survey_App.Models.Store", "Store")
                    .WithMany()
                    .HasForeignKey("StoreId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Store");
            });

            modelBuilder.Entity("EHM_Survey_App.Models.SurveyResponse", b =>
            {
                b.HasOne("EHM_Survey_App.Models.Store", "Store")
                    .WithMany()
                    .HasForeignKey("StoreId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Store");
            });
#pragma warning restore 612, 618
        }
    }
}
