services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/app

  frontend:
    build:
      context: ./FRONT-END
      dockerfile: Dockerfile
    ports:
      - '5139:80'
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
